name: README build

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.2
        with:
          files: chains/v2/chains.json

  build:
    runs-on: ubuntu-latest
    needs: check
    if: steps.changed-files.outputs.only_changed == 'true'
    steps:

      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate README file
        run: python ./scripts/generate-readme.py

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./chains/README.md
          git commit -m "Update networks"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: refs/heads/update-networks

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          source_branch: "update-networks"
          destination_branch: "master"
          pr_title: "Update network list"
          pr_body: |
              Update networks list in https://github.com/nova-wallet/nova-utils/tree/master/chains
              "👑 *An automated PR*"
          pr_reviewer: "stepanLav"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
