name: README build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.2
        with:
          files: chains/v2/chains.json

      - name: Install dependencies
        if: steps.changed-files.outputs.only_changed == 'true'
        run: pip install -r requirements.txt
      - name: Generate README file
        if: steps.changed-files.outputs.only_changed == 'true'
        run: python ./scripts/generate-readme.py

      - name: Commit files
        if: steps.changed-files.outputs.only_changed == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./chains/README.md
          git commit -m "Update networks"
      - name: Push changes
        if: steps.changed-files.outputs.only_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: refs/heads/update-networks

      - uses: repo-sync/pull-request@v2
        if: steps.changed-files.outputs.only_changed == 'true'
        name: pull-request
        with:
          source_branch: "update-networks"
          destination_branch: "master"
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "kingdonb"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Pull Request
      #   if: steps.changed-files.outputs.only_changed == 'true'
      #   uses: peter-evans/create-pull-request@v3.10.1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: Auto Pull Request
      #     title: Your desired title
      #     body: Auto-created Pull Request
      #     branch: ${{ github.ref }} # The branch where you commit
      #     base: master # Don't forget to specify the right base branch here
          # token: ${{ secrets.GITHUB_TOKEN }}
          # commit-message: Update network list
          # committer: GitHub <noreply@github.com>
          # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          # signoff: false
          # branch: update-network-list
          # delete-branch: true
          # title: 'Update network list'
          # body: |
          #   Update networks list in https://github.com/nova-wallet/nova-utils/tree/master/chains
          #   - Auto-generated by [create-pull-request][1]
          #   [1]: https://github.com/peter-evans/create-pull-request
          # base: master
          # assignees: stepanLav
          # draft: false
